### ISSUE TITLE
Need mk-ind-draft script

### ISSUE THREAD

**Issue by richsalz** [richsalz/ietf-gh-scripts#4]
Need a script, like mk-ietf-draft, to create drafts in a user's directory.  This will need much code re-used from that script, which might mean refactoring and packaging things as a python library which I have tried to avoid so far.

**Comment by MikeBishop** [comment]
Would like to highlight these scripts in my EDU talk in Prague, but since I suspect most of the audience will be individual draft authors, the applicability will be limited until this part exists.  If this could happen by a few weeks before Prague, that would be great.

**Comment by richsalz** [comment]
STill needs the refactoring cleanup.

**Comment by MikeBishop** [comment]
Also needs correct help text; asks for `--wg WGNAME` but then fails if that option is passed.
