### ISSUE TITLE
mk-ind-draft doesn't use the doc name specified

### ISSUE THREAD

**Issue by MikeBishop** [richsalz/ietf-gh-scripts#8]
`./mk-ind-draft --doc draft-bishop-litigious-flower -n <creds>` produced a repo named "draft-mikebishop-bishop-litigious-flower" and instructions about adding a document by that name.

I kind of get it -- if I just pass in "litigious-flower" then you're going to format the draft name semi-properly.  However, if I've specified a doc name that begins with "draft-", shouldn't that be the name used?

**Comment by richsalz** [comment]
I added an ```--asis``` flag to not standardize/mangle the name.  Does that seem good enough?  If not, please reopen this.
